const categories = [
    {
        title: "شوینده",
        slug: "detergents",
    },
    {
        title: "شیرینی، خشکبار و تنقلات",
        slug: "sweets-snacks",
    },
    {
        title: "نوشیدنی و عرقیجات",
        slug: "drinks",
    },
    {
        title: "ادویه، چاشنی، افزودنی",
        slug: "condiments",
    },
    {
        title: "لبنیات",
        slug: "dairy",
    },
    {
        title: "لوازم کودک",
        slug: "babies",
    },
    {
        title: "آرایشی و بهداشتی",
        slug: "cosmetics-hygiene",
    },
];

const stuffs = [
    {
        title: "پودر ماشین لباسشویی واش لند مدل Super Cleaning وزن 500 گرم",
        buyPrice: 30000,
        sellPrice: 40000,
        description: "",
        categoryId: 1,
    },
    {
        title: "ماست خامه ای پگاه مقدار 900 گرم",
        buyPrice: 50000,
        sellPrice: 56600,
        description: "",
        categoryId: 5,
    },
    {
        title: "شامپو صورت و بدن گلرنگ مدل بلوبری وزن 400 گرم",
        buyPrice: 58000,
        sellPrice: 66000,
        description: "",
        categoryId: 7,
    },
    {
        title: "خمیر دندان کرند مدل Cavity حجم 50 میلی لیتر",
        buyPrice: 16000,
        sellPrice: 20000,
        description: "",
        categoryId: 7,
    },
    {
        title: "شکلات تلخ 96 درصد باراکا - 300 گرم",
        buyPrice: 930000,
        sellPrice: 1000000,
        description: "",
        categoryId: 2,
    },
    {
        title: "شیر سویا مانداسوی با طعم طالبی - 1 لیتر",
        buyPrice: 120000,
        sellPrice: 132000,
        description: "",
        categoryId: 5,
    },
    {
        title: "شامپو بچه فیروز با عصاره بابونه حجم 300 میلی لیتر",
        buyPrice: 42000,
        sellPrice: 50000,
        description: "",
        categoryId: 6,
    },
    {
        title: "دسر نوشیدنی عسل دنت حجم 200 میلی لیتر",
        buyPrice: 26000,
        sellPrice: 29500,
        description: "",
        categoryId: 5,
    },
    {
        title: "شامپو بچه اکتیو مدل Spider Man مقدار 280 گرم",
        buyPrice: 44000,
        sellPrice: 50000,
        description: "",
        categoryId: 6,
    },
    {
        title: "دستمال کاغذی 250 برگ ایزی پیک مدل دولایه",
        buyPrice: 44000,
        sellPrice: 50000,
        description: "",
        categoryId: 7,
    },
    {
        title: "پودر لباسشویی پرسيل مدل پریمیوم وزن 5 کیلوگرم",
        buyPrice: 430000,
        sellPrice: 450000,
        description: "",
        categoryId: 1,
    },
    {
        title: "ادویه ماهی گرین فیلد - 85 گرم",
        buyPrice: 140000,
        sellPrice: 175000,
        description: "",
        categoryId: 4,
    },
    {
        title: "هل سبز تواضع - 50 گرم",
        buyPrice: 240000,
        sellPrice: 270000,
        description: "",
        categoryId: 4,
    },
    {
        title: "قرص ماشین ظرفشویی بینگو مدل ALL IN ONE بسته 24 عددی",
        buyPrice: 170000,
        sellPrice: 180000,
        description: "",
        categoryId: 1,
    },
    {
        title: "دسر نوشیدنی شکلات دنت حجم 1 لیتر",
        buyPrice: 110000,
        sellPrice: 133000,
        description: "",
        categoryId: 5,
    },
    {
        title: "نوشیدنی بدون گاز پرتقال کیوب لند - 300 میلی لیتر",
        buyPrice: 33000,
        sellPrice: 40000,
        description: "",
        categoryId: 3,
    },
    {
        title: "مایع دستشویی لوکس مدل رایحه یاس و گاردنیا حجم 500 میلی لیتر",
        buyPrice: 90000,
        sellPrice: 100000,
        description: "",
        categoryId: 1,
    },
    {
        title: "عرق پاستوریزه بید مشک اصالت - 0.4 لیتر",
        buyPrice: 79000,
        sellPrice: 88000,
        description: "",
        categoryId: 3,
    },
    {
        title: "پنیر پیتزا تاپینگ کانیار - 800 گرم",
        buyPrice: 235000,
        sellPrice: 260000,
        description: "",
        categoryId: 5,
    },
    {
        title: "ژل مو کاسپین مدل Classic Hold حجم 150 میلی لیتر",
        buyPrice: 70000,
        sellPrice: 77000,
        description: "",
        categoryId: 7,
    },
    {
        title: "نرم کننده مو مای مدل Keep Fresh حجم 400 میلی لیتر",
        buyPrice: 88000,
        sellPrice: 93500,
        description: "",
        categoryId: 7,
    },
    {
        title: "صابون نوزاد و کودک پینو بیبی مدل کرمی وزن 75 گرم",
        buyPrice: 22000,
        sellPrice: 29000,
        description: "",
        categoryId: 6,
    },
    {
        title: "شامپو سر و بدن شون مدل Mojito حجم 400 میلی لیتر",
        buyPrice: 82000,
        sellPrice: 89500,
        description: "",
        categoryId: 7,
    },
    {
        title: "نوشیدنی پرتقال سن ایچ مقدار 200 میلی لیتر",
        buyPrice: 30000,
        sellPrice: 36000,
        description: "",
        categoryId: 3,
    },
    {
        title: "شامپو بچه فیروز با عصاره‌ اسطوخودوس حجم 200 میلی لیتر",
        buyPrice: 29000,
        sellPrice: 34000,
        description: "",
        categoryId: 6,
    },
    {
        title: "عرق بهارنارنج گلستان - 500 میلی لیتر",
        buyPrice: 65000,
        sellPrice: 72000,
        description: "",
        categoryId: 3,
    },
    {
        title: "پودر لباسشویی پرسيل مدل لوندر وزن 5 کیلوگرم",
        buyPrice: 522000,
        sellPrice: 550000,
        description: "",
        categoryId: 1,
    },
    {
        title: "پودر و پرک سوخاری فلفلی هاتی کارا - 100 گرم مجموعه 2 عددی",
        buyPrice: 40000,
        sellPrice: 50000,
        description: "",
        categoryId: 4,
    },
    {
        title: "اسنک چرخی مزمز - 85 گرم ",
        buyPrice: 18000,
        sellPrice: 25000,
        description: "",
        categoryId: 2,
    },
    {
        title: "آلبالو ترش مانی - 65 گرم",
        buyPrice: 22000,
        sellPrice: 30000,
        description: "",
        categoryId: 2,
    },
    {
        title: "مایع لباسشویی کودک اکتیو مدل لاندری - وزن 1500 گرم",
        buyPrice: 120000,
        sellPrice: 133000,
        description: "",
        categoryId: 6,
    },
    {
        title: "بیسکویت با طعم پرتقال دلاتو - 900 گرم",
        buyPrice: 90000,
        sellPrice: 100000,
        description: "",
        categoryId: 2,
    },
    {
        title: "پودر ماشین لباسشویی بینگو مدل Green وزن 500 گرم",
        buyPrice: 34000,
        sellPrice: 42000,
        description: "",
        categoryId: 1,
    },
    {
        title: "شامپو مو شاوما مدل For Men حجم 400 میلی لیتر",
        buyPrice: 140000,
        sellPrice: 152000,
        description: "",
        categoryId: 7,
    },
    {
        title: "ماست سبزیجات کاله - 750 گرم",
        buyPrice: 75000,
        sellPrice: 82000,
        description: "",
        categoryId: 5,
    },
    {
        title: "آبمیوه پرتقال سان استار حجم 240 میلی لیتر",
        buyPrice: 27000,
        sellPrice: 33000,
        description: "",
        categoryId: 3,
    },
    {
        title: "ترشی سیر مروارید بیژن - 630 گرم",
        buyPrice: 160000,
        sellPrice: 180000,
        description: "",
        categoryId: 4,
    },
    {
        title: "ماست موسیردار چکیده پگاه مقدار 500 گرم",
        buyPrice: 58000,
        sellPrice: 66000,
        description: "",
        categoryId: 5,
    },
    {
        title: "سس فلفل سبز تند مهرام - 320 گرم",
        buyPrice: 75000,
        sellPrice: 85000,
        description: "",
        categoryId: 4,
    },
    {
        title: "مایع نرم کننده لباس کودک فیروز مدل 001 مقدار 950 گرم",
        buyPrice: 40000,
        sellPrice: 47000,
        description: "",
        categoryId: 6,
    },
    {
        title: "مایع جرم گیر اکتیو کد 01 حجم 750 میلی لیتر ",
        buyPrice: 51000,
        sellPrice: 60000,
        description: "",
        categoryId: 1,
    },
    {
        title: "سس تند فلفل قرمز بهروز - 225 گرم",
        buyPrice: 58000,
        sellPrice: 66000,
        description: "",
        categoryId: 4,
    },
    {
        title: "بیسکویت کاکائویی با کرم وانیلی سلامت - 400 گرم",
        buyPrice: 56000,
        sellPrice: 66000,
        description: "",
        categoryId: 2,
    },
    {
        title: "شامپو بچه گلرنگ مدل Blue مقدار 210 گرم",
        buyPrice: 35000,
        sellPrice: 40000,
        description: "",
        categoryId: 6,
    },
    {
        title: "پسته صادراتی فراوری شده بدون نمک تواضع  - 200 گرم",
        buyPrice: 275000,
        sellPrice: 300000,
        description: "",
        categoryId: 2,
    },
    {
        title: "شامپو سر نوزاد و کودک پینو بیبی مدل pink وزن 200 گرم",
        buyPrice: 49000,
        sellPrice: 55000,
        description: "",
        categoryId: 6,
    },
    {
        title: "نکتار میوه های گرمسیری سن ایچ حجم 750 میلی لیتر",
        buyPrice: 52000,
        sellPrice: 60000,
        description: "",
        categoryId: 3,
    },
    {
        title: "پوشک بچه هانیز سایز 5 بسته 10 عددی",
        buyPrice: 79000,
        sellPrice: 88000,
        description: "",
        categoryId: 6,
    },
    {
        title: "خیارشور سوپر ویژه مکنزی - 660 گرم",
        buyPrice: 150000,
        sellPrice: 165000,
        description: "",
        categoryId: 4,
    },
    {
        title: "ماءالشعیر جوجو با طعم لیمو - 330 میلی لیتر",
        buyPrice: 30000,
        sellPrice: 35000,
        description: "",
        categoryId: 3,
    },
    {
        title: "پنیر لبنه پاک - 300 گرم",
        buyPrice: 60000,
        sellPrice: 66200,
        description: "",
        categoryId: 5,
    },
    {
        title: "رب گوجه فرنگی بیژن مقدار 680 گرم",
        buyPrice: 53000,
        sellPrice: 60000,
        description: "",
        categoryId: 4,
    },
    {
        title: "شکلات مدل مونت کارلو باراکا - 170 گرم",
        buyPrice: 370000,
        sellPrice: 400000,
        description: "",
        categoryId: 2,
    },
    {
        title: "شامپو ضد شوره مو مدیلن مدل 202 حجم 200 میلی لیتر",
        buyPrice: 82000,
        sellPrice: 90000,
        description: "",
        categoryId: 7,
    },
    {
        title: "شامپو صحت مدل کلاژن 1 کیلوگرم",
        buyPrice: 130000,
        sellPrice: 145000,
        description: "",
        categoryId: 7,
    },
    {
        title: "بادام زمینی فلفلی مزمز مقدار 35 گرم",
        buyPrice: 15000,
        sellPrice: 20000,
        description: "",
        categoryId: 2,
    },
    {
        title: "کنسرو گوجه فرنگی اویلا مقدار 800 گرم",
        buyPrice: 75000,
        sellPrice: 85000,
        description: "",
        categoryId: 4,
    },
    {
        title: "شکلات تلخ 72 درصد پارمیدا - 80 گرم",
        buyPrice: 172000,
        sellPrice: 190000,
        description: "",
        categoryId: 2,
    },
    {
        title: "مایع دستشویی کرمی اکتیو مدل Lovely Scent وزن 2000 گرم",
        buyPrice: 160000,
        sellPrice: 190000,
        description: "",
        categoryId: 1,
    },
    {
        title: "شکلات مدل آبرنگ باراکا - 225 گرم",
        buyPrice: 370000,
        sellPrice: 400000,
        description: "",
        categoryId: 2,
    },
    {
        title: "دستمال کاغذی 100 برگ پاپیا مدل 03",
        buyPrice: 18000,
        sellPrice: 22000,
        description: "",
        categoryId: 7,
    },
    {
        title: "شیر پرچرب روزانه- 1 لیتر",
        buyPrice: 48000,
        sellPrice: 55000,
        description: "",
        categoryId: 5,
    },
    {
        title: "نرم کننده موی سر اوه مدل Pro Vitamin B5 مقدار 1000 گرم",
        buyPrice: 85000,
        sellPrice: 93300,
        description: "",
        categoryId: 7,
    },
    {
        title: "شامپو بچه اکتیو مدل Soft وزن 250 گرم",
        buyPrice: 38000,
        sellPrice: 45000,
        description: "",
        categoryId: 6,
    },
    {
        title: "رب گوجه فرنگی مکنزی - 1.5 کیلوگرم",
        buyPrice: 140000,
        sellPrice: 155000,
        description: "",
        categoryId: 4,
    },
    {
        title: "فلفل سیاه هاتی کارا - 500 گرم",
        buyPrice: 520000,
        sellPrice: 555000,
        description: "",
        categoryId: 4,
    },
    {
        title: "نکتار سیب سن ایچ - 750 میلی لیتر",
        buyPrice: 55000,
        sellPrice: 62000,
        description: "",
        categoryId: 3,
    },
    {
        title: "پنیر دیپ دودی کالین - 800 گرم",
        buyPrice: 440000,
        sellPrice: 492000,
        description: "",
        categoryId: 5,
    },
    {
        title: "آب برای شیرخواران و نوزادان ماجان - 330 میلی‌لیتر",
        buyPrice: 18000,
        sellPrice: 24000,
        description: "",
        categoryId: 6,
    },
];

const people = [
    {
        fullname: "محمد موسوی",
        phone: "09123456789",
        address: "آدرس تستی",
    },
    {
        fullname: "عباس مقدم",
        phone: "09345678964",
        address: "آدرس تستی",
    },
    {
        fullname: "فرهاد وحیدی",
        phone: "09998787412",
        address: "آدرس تستی",
    },
    {
        fullname: "سعید حیدری",
        phone: "09123456824",
        address: "آدرس تستی",
    },
    {
        fullname: "کاوه رایگان",
        phone: "09884254623",
        address: "آدرس تستی",
    },
    {
        fullname: "امیر مقدم",
        phone: "09365554441",
        address: "آدرس تستی",
    },
    {
        fullname: "احمد موسوی",
        phone: "09874256524",
        address: "آدرس تستی",
    },
    {
        fullname: "کیوان خوندل",
        phone: "09365854563",
        address: "آدرس تستی",
    },
    {
        fullname: "ارسلان مقدم",
        phone: "09785552135",
        address: "آدرس تستی",
    },
    {
        fullname: "حسین نیکنژاد",
        phone: "09987522554",
        address: "آدرس تستی",
    },
    {
        fullname: "حمید موسوی",
        phone: "09745552698",
        address: "آدرس تستی",
    },
    {
        fullname: "امین رفیعی",
        phone: "09877822474",
        address: "آدرس تستی",
    },
    {
        fullname: "امیر عظیمی",
        phone: "09887468524",
        address: "آدرس تستی",
    },
];

const invoices = [
    {
        type: "buy",
        date: "2024-12-06",
        invoiceNumber: 1001,
        description: "",
        totalPrice: 2850000,
        personId: 1,
    },
    {
        type: "sell",
        date: "2024-12-07",
        invoiceNumber: 1002,
        description: "",
        totalPrice: 5180000,
        personId: 3,
    },
    {
        type: "buy",
        date: "2024-12-07",
        invoiceNumber: 1003,
        description: "",
        totalPrice: 2490000,
        personId: 1,
    },
    {
        type: "buy",
        date: "2024-12-08",
        invoiceNumber: 1004,
        description: "",
        totalPrice: 1980000,
        personId: 4,
    },
    {
        type: "sell",
        date: "2024-12-08",
        invoiceNumber: 1005,
        description: "",
        totalPrice: 4270000,
        personId: 8,
    },
    {
        type: "buy",
        date: "2024-12-09",
        invoiceNumber: 1006,
        description: "",
        totalPrice: 1142000,
        personId: 2,
    },
];

const invoiceItems = [
    {
        unitPrice: 30000,
        quantity: 2,
        invoiceId: 1,
        stuffId: 1,
    },
    {
        unitPrice: 930000,
        quantity: 3,
        invoiceId: 1,
        stuffId: 5,
    },
    {
        unitPrice: 20000,
        quantity: 1,
        invoiceId: 2,
        stuffId: 4,
    },
    {
        unitPrice: 1000000,
        quantity: 3,
        invoiceId: 2,
        stuffId: 5,
    },
    {
        unitPrice: 180000,
        quantity: 12,
        invoiceId: 2,
        stuffId: 14,
    },
    {
        unitPrice: 120000,
        quantity: 11,
        invoiceId: 3,
        stuffId: 6,
    },
    {
        unitPrice: 110000,
        quantity: 3,
        invoiceId: 3,
        stuffId: 15,
    },
    {
        unitPrice: 30000,
        quantity: 40,
        invoiceId: 4,
        stuffId: 1,
    },
    {
        unitPrice: 120000,
        quantity: 3,
        invoiceId: 4,
        stuffId: 6,
    },
    {
        unitPrice: 30000,
        quantity: 14,
        invoiceId: 4,
        stuffId: 50,
    },
    {
        unitPrice: 20000,
        quantity: 12,
        invoiceId: 5,
        stuffId: 4,
    },
    {
        unitPrice: 66000,
        quantity: 11,
        invoiceId: 5,
        stuffId: 3,
    },
    {
        unitPrice: 132000,
        quantity: 12,
        invoiceId: 5,
        stuffId: 6,
    },
    {
        unitPrice: 180000,
        quantity: 4,
        invoiceId: 5,
        stuffId: 14,
    },
    {
        unitPrice: 50000,
        quantity: 20,
        invoiceId: 5,
        stuffId: 10,
    },
    {
        unitPrice: 70000,
        quantity: 12,
        invoiceId: 3,
        stuffId: 20,
    },
    {
        unitPrice: 30000,
        quantity: 7,
        invoiceId: 6,
        stuffId: 1,
    },
    {
        unitPrice: 58000,
        quantity: 10,
        invoiceId: 6,
        stuffId: 3,
    },
    {
        unitPrice: 16000,
        quantity: 22,
        invoiceId: 6,
        stuffId: 4,
    },
];

export { categories, stuffs, people, invoices, invoiceItems };
